root_dir: mbatch_test

globals:
  global: data/globals.yml

gitcheck_pkgs:
  - numpy
  - healpy
#  - pymaster

stages:
# Compute mask's MCM
  mcm:
    exec: python3
    script: pipeline/mcmer.py
    globals:
      - global
# Filter all power-law sims
  filter_PL:
    exec: python3
    script: pipeline/filterer_toast.py
    globals:
      - global
    options:
      schedule: data/schedules/schedule_sat.fixed_el.1day.txt
      bands: SAT_f090
      telescope: SAT1
      sample-rate: 40
      thinfp: 8
      group-size: 8
      first-sim: 0
      num-sims: 2
      sim-sorter: pl_sim_names
    parallel:
      nproc: 1
      memory_gb: 4
      min_threads: 1
      walltime: 00:15:00
# Filter all val sims
  filter_val:
    exec: python3
    script: pipeline/filterer_toast.py
    globals:
      - global
    options:
      schedule: data/schedules/schedule_sat.fixed_el.1day.txt
      bands: SAT_f090
      telescope: SAT1
      sample-rate: 40
      thinfp: 8
      group-size: 8
      first-sim: 0
      num-sims: 2
      sim-sorter: val_sim_names
    parallel:
      nproc: 1
      memory_gb: 4
      min_threads: 1
      walltime: 00:15:00
# Compute pseudo-Cl of input power-law sims
  pcl_PL_in:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    options:
      first-sim: 0
      num-sims: 2
      sim-sorter: pl_sim_names_EandB
      sim-type: input
      beam-fwhm: 0.5

# Compute pseudo-Cl of filtered power-law sims
  pcl_PL_filt:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    depends:
      - filter_PL
    options:
      first-sim: 0
      num-sims: 2
      sim-sorter: pl_sim_names_EandB
      sim-type: filtered
      filtered-with-toast: True
      beam-fwhm: 0.5

# Compute pseudo-Cl of input validation sims
  pcl_val_in:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    options:
      first-sim: 0
      num-sims: 2
      sim-sorter: val_sim_names
      sim-type: input
      beam-fwhm: 0.5

# Compute pseudo-Cl of filtered validation sims
  pcl_val_filt:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    depends:
      - filter_val
    options:
      first-sim: 0
      num-sims: 2
      sim-sorter: val_sim_names
      sim-type: filtered
      filtered-with-toast: True
      beam-fwhm: 0.5

# Estimate transfer function and bandpower
# window functions from PL sim products
  transfer:
    exec: python3
    script: pipeline/transfer.py
    globals:
      - global
    depends:
      - mcm
      - pcl_PL_in
      - pcl_PL_filt
    options:
      use-theory: True

# Compute Cl of filtered validation sims
# corrected for the transfer function
  cl_val:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    depends:
      - filter_val
      - transfer
    options:
      first-sim: 0
      num-sims: 2
      sim-sorter: val_sim_names
      sim-type: decoupled
      correct-transfer: True
      filtered-with-toast: True
      beam-fwhm: 0.5

# Compare Cl of validation sims with theory
# convolved with bpw window functions
  transfer_val:
    exec: python3
    script: pipeline/transfer_validator.py
    globals:
      - global
    depends:
      - pcl_val_in
      - pcl_val_filt
      - transfer
      - cl_val
    options:
      transfer-threshold: 0.05